### ISSUE TITLE
total balance 0.00 

### ISSUE THREAD

**Issue by ahmednazarchishti** [eosclassic/mist#1]
HI,
after recent update, the total balance is shwn as 0.0 . while the balance on each account is correct. any suggestion to correct this issue? Also wanted to add that my trial wallet contract, which i created to check if it work also has dissapeared.

**Comment by eosclassicteam** [comment]
@ahmednazarchishti @cliff75421 Hello, thanks for the report.

We are investigating the issue regarding balance error, it will be patched on the next release

**Comment by eosclassicteam** [comment]
Now fixed on version 0.10.2, thanks for reporting the bug, @ahmednazarchishti @cliff75421 ! Much appreciated 👍
